### ISSUE TITLE
Passing seed arg to env.reset()

### ISSUE THREAD

**Issue by enjeeneer** [rdnfn/bauwerk#15]
* bauwerk version: 0.2.1
* Python version: 3.8.12
* Operating System: macOS

### Description

When I pass a `seed` to `env.reset(seed=seed)` I receive an error stating Bauwerk was not expected more that one argument to env.reset(). At first glance, the error may be in line 491 of `bauwerk/envs/solar_battery_house.py` where the gym-compatible env is not expecting a seed arg. I may be wrong though.

As a wider point, do we really want set a seed using `.reset()` rather than `.make()`? Should the seed not be a property of the `env` upon instantiation, rather than changed when we reset the env to receive the first obs? 

### What I Did

```
env = gym.make("bauwerk/BuildDistB-v0")
obs = env.reset(seed=123)

File ~/miniforge3/envs/odes/lib/python3.8/site-packages/gym/wrappers/order_enforcing.py:16, in OrderEnforcing.reset(self, **kwargs)
     14 def reset(self, **kwargs):
     15     self._has_reset = True
---> 16     return self.env.reset(**kwargs)

TypeError: reset() got an unexpected keyword argument 'seed'
```

**Comment by rdnfn** [comment]
Thanks a lot for raising this @enjeeneer! We already discussed this but for future reference and other people: this is an issue with the Gym API. In version 0.21 and before the reset() does not accept the seed argument. Bauwerk is flexible and can adapt to whatever Gym version you install (tested from v0.21 upwards), but this also means some examples shown in the docs only work with certain Gym versions. Notably, stable baselines 3 has (at this point) not been updated yet, and will therefore, when installed, revert to an old Gym API version as in this issue. See [the official release notes](https://github.com/openai/gym/releases) for some discussion on the changes to the Gym API.

As this is expected behaviour when gym v0.21 is installed, I am closing this issue.
